openapi: 3.0.0
info:
  description: BFF for Free Powder
  version: 1.0.0
  title: Free Powder API

servers:
  - url: /api

paths:
  /auth/signin:
    $ref: "./paths/auth-sign-in.yml"
  /auth/signup:
    $ref: "./paths/auth-sign-up.yml"
  /auth/signout:
    $ref: "./paths/auth-sign-out.yml"
  /users/me:
    $ref: "./paths/users-me.yml"
  /users:
    $ref: "./paths/users-list.yml"
  /users/update:
    $ref: "./paths/users-update.yml"
  /wierzbianski/content:
    $ref: "./paths/wierzbianski-list.yml"
  /wierzbianski/content/{contentId}:
    $ref: "./paths/wierzbianski-update.yml"
